name: API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest requests

      - name: Start FastAPI server in background
        run: |
          nohup python apiserver.py > server.log 2>&1 &
          sleep 5
          cat server.log  # Optional: helps debug if the server fails
        env:
          PYTHONUNBUFFERED: 1

      - name: Run tests with pytest
        run: pytest tests/testAutomationPytest.py
