name: FastAPI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest requests

      - name: Start FastAPI server in background
        run: |
          nohup python app/apiserver.py > server.log 2>&1 &
        env:
          PYTHONUNBUFFERED: 1

      - name: Wait until FastAPI is up
        run: |
          echo "Waiting for FastAPI server..."
          for i in {1..10}; do
            if curl -s http://127.0.0.1:8000/docs > /dev/null; then
              echo "Server is up!"
              break
            fi
            echo "Retrying in 2s..."
            sleep 2
          done
          curl -I http://127.0.0.1:8000/docs

      - name: Run pytest
        run: pytest tests/testAutomationPytest.py
